[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/generate-game"
  to = "/.netlify/functions/api/generate-game"
  status = 200

[[redirects]]
  from = "/save-questions"
  to = "/.netlify/functions/api/save-questions"
  status = 200

[[redirects]]
  from = "/generator"
  to = "/.netlify/functions/api/generator"
  status = 200
